# run: conda env export > environment.yml --no-builds
name: smile
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2023.5.7
  - dlib=19.24.2
  - intel-openmp=2023.1.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libpng=1.6.39
  - libxml2=2.11.4
  - libzlib=1.2.13
  - mkl=2022.1.0
  - numpy=1.24.4
  - openssl=3.1.1
  - pip=23.1.2
  - pthreads-win32=2.9.1
  - python=3.8.16
  - python_abi=3.8
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tbb=2021.9.0
  - ucrt=10.0.22621.0
  - vc=14.2
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wheel=0.38.4
  - pip:
      - click==8.1.3
      - colorama==0.4.6
      - contourpy==1.1.0
      - cycler==0.11.0
      - face-recognition==1.3.0
      - face-recognition-models==0.3.0
      - fonttools==4.40.0
      - importlib-resources==5.12.0
      - kiwisolver==1.4.4
      # - matplotlib==3.7.1
      - opencv-python==4.8.0.74
      - packaging==23.1
      - pillow==10.0.0
      - pyparsing==3.1.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.1
      - python-dateutil==2.8.2
      - six==1.16.0
      - zipp==3.15.0
